apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: board-api
  namespace: api
  labels:
    app: board-api
    
spec:
  replicas: 2
  selector:
    matchLabels:
      app: board-api

  template:
    metadata:
      labels:
        app: board-api
          
    spec:
      containers:
      - name: board-api
        #image: jacksonkim/board-api
        image: gcr.io/durable-will-304110/board-api
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8001
           
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
  
    blueGreen:
      previewService: board-api-svc-preview
      activeService: board-api-svc-active
      #autoPromotionEnabled: true
      autoPromotionEnabled: false
      previewReplicaCount: 1
      scaleDownDelaySeconds: 60 

---
kind: Service
apiVersion: v1
metadata:
  name: board-api-svc-active
spec:
  selector:
    app: board-api
  
  ports:
  - protocol: TCP
    port: 8081
    targetPort: http

  #type: NodePort
  #ports:
  #- protocol: TCP
  #  port: 8001
  #  targetPort: http
  #  nodePort: 30081

  type: LoadBalancer
  #ports:
  #- port: 8081

---
kind: Service
apiVersion: v1
metadata:
  name: board-api-svc-preview
spec:
  selector:
    app: board-api
  
  ports:
  - protocol: TCP
    port: 8082
    targetPort: http

  #type: NodePort
  #ports:
  #- protocol: TCP
  #  port: 8001
  #  targetPort: http
  #  nodePort: 30082

  type: LoadBalancer
  #ports:
  #- port: 8082