apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: board-api
  namespace: api
  labels:
    app: board-api
    
spec:
  replicas: 2
  selector:
    matchLabels:
      app: board-api

  template:
    metadata:
      labels:
        app: board-api
          
    spec:
      containers:
      - name: board-api
        image: jacksonkim/board-api
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8001
           
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
  
    blueGreen:
      previewService: board-api-svc-preview
      activeService: board-api-svc-active
      autoPromotionEnabled: false
      previewReplicaCount: 1
      scaleDownDelaySeconds: 60 

---
kind: Service
apiVersion: v1
metadata:
  name: board-api-svc-active
spec:
  selector:
    app: board-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30081
  type: NodePort

---
kind: Service
apiVersion: v1
metadata:
  name: board-api-svc-preview
spec:
  selector:
    app: board-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30082
  type: NodePort