apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
resources:
- board-api-rollout.yaml
 
images:
#- name: jacksonkim/board-api
- name: gcr.io/durable-will-304110/board-api
  newTag: "1.0"